blogicum/blog/urls.py
from django.urls import path

from blog import views
from blog.views import (
    PostCreateView, UserProfileUpdateView, PostUpdateView,
    PostDeleteView, CommentCreateView,
    CommentUpdateView, CommentDeleteView
)

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:id>/', views.post_detail, name='post_detail'),
    path('category/<slug:category_slug>/',
         views.category_posts, name='category_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/create/', PostCreateView.as_view(), name='create_post'),
    path(
        'edit_profile/<int:pk>/',
        UserProfileUpdateView.as_view(),
        name='edit_profile'
    ),
    path('posts/<int:pk>/edit/', PostUpdateView.as_view(), name='edit_post'),
    path(
        'posts/<int:pk>/delete/',
        PostDeleteView.as_view(),
        name='delete_post'
    ),
    path(
        'posts/<int:post_id>/comment/',
        CommentCreateView.as_view(),
        name='add_comment'
    ),
    path(
        'posts/<int:post_id>/edit_comment/<int:pk>/',
        CommentUpdateView.as_view(),
        name='edit_comment'
    ),
    path(
        'posts/<int:post_id>/delete_comment/<int:pk>/',
        CommentDeleteView.as_view(),
        name='delete_comment'
    ),
]

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.internal_server_error'

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('pages/', include('pages.urls', namespace='pages')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('blog:index'),
        ),
        name='registration',
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogicum/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone


User = get_user_model()


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
            is_published=True,
            pub_date__lte=timezone.now(),
            category__is_published=True,
        )


class PublishedModel(models.Model):
    is_published = models.BooleanField(
        'Опубликовано',
        default=True,
        help_text='Снимите галочку, чтобы скрыть публикацию.',
    )

    created_at = models.DateTimeField('Добавлено', auto_now_add=True)

    class Meta:
        abstract = True


class Category(PublishedModel):
    title = models.CharField('Заголовок', max_length=256)
    description = models.TextField('Описание')
    slug = models.SlugField(
        'Идентификатор',
        unique=True,
        help_text=(
            'Идентификатор страницы для URL; '
            'разрешены символы латиницы, цифры, дефис и подчёркивание.'
        )
    )

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'

    def __str__(self) -> str:
        return self.title


class Location(PublishedModel):
    name = models.CharField('Название места', max_length=256)

    class Meta:
        verbose_name = 'местоположение'
        verbose_name_plural = 'Местоположения'

    def __str__(self) -> str:
        return self.name


class Post(PublishedModel):
    title = models.CharField('Заголовок', max_length=256)
    text = models.TextField('Текст')
    pub_date = models.DateTimeField(
        'Дата и время публикации',
        help_text=(
            'Если установить дату и время в '
            'будущем — можно делать отложенные публикации.'
        )
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор публикации',
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.SET_NULL,
        related_name='posts',
        null=True,
        blank=True,
        verbose_name='Местоположение',
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Категория',
        null=True,
        blank=False,
    )
    image = models.ImageField('Фото', upload_to='blogicum_images', blank=True)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = 'Публикации'
        ordering = ('-pub_date',)

    def __str__(self) -> str:
        return self.title


TEXT_SLICE = 15


class Comment(models.Model):
    text = models.TextField('текст')
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'

    def __str__(self) -> str:
        return (self.text[:TEXT_SLICE] + '...'
                ) if len(self.text) > TEXT_SLICE else self.text

blogicum/blog/forms.py
from django import forms
from django.utils import timezone
from django.forms.widgets import DateTimeInput
from django.contrib.auth import get_user_model

from blog.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'category', 'location', 'pub_date', 'image')
        widgets = {
            'pub_date': DateTimeInput(
                attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'
            ),
        }

    def clean_pub_date(self):
        pub_date = self.cleaned_data.get('pub_date')
        self.instance.is_published = pub_date and pub_date < timezone.now()
        return pub_date


User = get_user_model()


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

blogicum/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Count
from django.conf import settings
from django.http import HttpResponseRedirect

from blog.models import Post, Category, Comment, User
from blog.forms import PostForm, UserProfileForm, CommentForm


def index(request):
    post_list = (
        Post.published.annotate(
            comment_count=Count('comments')
        ).order_by('-pub_date')
    )
    paginator = Paginator(post_list, settings.PAX_POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'blog/index.html', {'page_obj': page_obj})


def post_detail(request, id):
    template = 'blog/detail.html'
    post = get_object_or_404(Post, id=id)
    if not request.user.is_authenticated or request.user != post.author:
        post = get_object_or_404(Post.published.filter(
            id=id,
        ).annotate(comment_count=Count('comments')))

    comments = post.comments.all()
    comment_form = CommentForm()
    context = {'post': post, 'comments': comments, 'form': comment_form}
    return render(request, template, context)


def category_posts(request, category_slug):
    category = get_object_or_404(
        Category,
        slug=category_slug,
        is_published=True
    )
    category_posts = Post.published.filter(
        category=category
    )
    paginator = Paginator(category_posts, settings.PAX_POSTS_PER_PAGE)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'category': category, 'page_obj': page_obj}
    return render(request, 'blog/category.html', context)


def profile(request, username):
    profile = get_object_or_404(User, username=username)
    if request.user == profile:
        user_posts = profile.posts.annotate(
            comment_count=Count('comments')
        ).order_by('-pub_date')
    else:
        user_posts = Post.published.filter(
            author=profile.id
        ).annotate(
            comment_count=Count('comments')
        ).order_by('-pub_date')

    paginator = Paginator(user_posts, settings.PAX_POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'profile': profile, 'page_obj': page_obj}
    return render(request, 'blog/profile.html', context)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(
            'blog:profile',
            kwargs={'username': self.request.user.username}
        )


class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'blog/user.html'

    def get_object(self, queryset=None):
        return get_object_or_404(User, pk=self.request.user.pk)

    def form_valid(self, form):
        form.save()
        return redirect(reverse(
            'blog:profile', kwargs={'username': self.request.user.username})
        )


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/create.html'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            return HttpResponseRedirect(
                reverse('blog:post_detail', args=[obj.id])
            )
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('blog:post_detail', kwargs={'id': self.object.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_edit'] = True
        return context


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    form_class = PostForm
    template_name = 'blog/create.html'
    success_url = reverse_lazy('blog:index')

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            return HttpResponseRedirect(
                reverse('blog:post_detail', args=[obj.id])
            )
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_delete'] = True
        context['post'] = self.get_object()
        return context


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        post = get_object_or_404(Post, pk=self.kwargs.get('post_id'))
        form.instance.post = post
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'blog:post_detail',
            kwargs={'id': self.object.post.id}
        )


class CommentUpdateView(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/comment.html'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            return HttpResponseRedirect(
                reverse('blog:post_detail', args=[obj.post.id])
            )
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy(
            'blog:post_detail', kwargs={'id': self.object.post.id}
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_edit'] = True
        return context


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = 'blog/comment.html'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            return HttpResponseRedirect(
                reverse('blog:post_detail', args=[obj.post.id])
            )
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'id': self.object.post.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_delete'] = True
        return context

blogicum/templates/blog/category.html
{% extends "base.html" %}
{% block title %}
  Публикации в категории {{ category.title }}
{% endblock %}
{% block content %}
  <h1 class="text-center">Публикации в категории - {{ category.title }}</h1>
  <p class="col-6 offset-3 mb-5 lead text-center">{{ category.description }}</p>
  {% for post in page_obj %}
    <article class="mb-5">  
      {% include "includes/post_card.html" %}
    </article>   
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

blogicum/templates/blog/comment.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if is_edit %}
    Редактирование комментария
  {% elif is_delete %}
    Удаление комментария
  {% endif %}
{% endblock %}
{% block content %}
  {% if user.is_authenticated %}
    <div class="col d-flex justify-content-center">
      <div class="card" style="width: 40rem;">
        <div class="card-header">
          {% if is_edit %}
            Редактирование комментария
          {% elif is_delete %}
            Удаление комментария
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post"
            {% if is_edit %}
              action="{% url 'blog:edit_comment' comment.post_id comment.id %}"
            {% endif %}>
            {% csrf_token %}
            {% if not is_delete %}
              {% bootstrap_form form %}
              {% bootstrap_button button_type="submit" content="Редактировать" %}
            {% else %}
              <p>{{ comment.text }}</p>
              {% bootstrap_button button_type="submit" content="Удалить" %}
            {% endif %}
          </form>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

blogicum/templates/blog/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if is_edit %}
    Редактирование публикации
  {% elif is_delete %}
    Удаление публикации
  {% else %}
    Добавление публикации
  {% endif %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        {% if is_edit %}
          Редактирование публикации
        {% elif is_delete %}
          Удаление публикации
        {% else %}
          Добавление публикации
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data" 
          action="{% if is_edit %}{% url 'blog:edit_post' post.id %}{% elif is_delete %}{% url 'blog:delete_post' post.id %}{% else %}{% url 'blog:create_post' %}{% endif %}">
          {% csrf_token %}
          {% if not is_delete %}
            {% bootstrap_form form %}
            {% bootstrap_button button_type="submit" content="Редактировать" %}
          {% else %}
            <article>
              {% if post.image %}
                <a href="{{ post.image.url }}" target="_blank">
                  <img class="border-3 rounded img-fluid img-thumbnail mb-2" src="{{ post.image.url }}">
                </a>
              {% endif %}
              <p>{{ post.pub_date|date:"d E Y" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
              <h3>{{ post.title }}</h3>
              <p>{{ post.text|linebreaksbr }}</p>
            </article>
            {% bootstrap_button button_type="submit" content="Удалить" %}
          {% endif %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

blogicum/templates/blog/detail.html
{% extends "base.html" %}
{% block title %}
  {{ post.title }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %} |
  {{ post.pub_date|date:"d E Y" }}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        {% if post.image %}
          <a href="{{ post.image.url }}" target="_blank">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ post.image.url }}">
          </a>
        {% endif %}
        <h5 class="card-title">{{ post.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            {% if not post.is_published %}
              <p class="text-danger">Пост снят с публикации админом</p>
            {% elif not post.category.is_published %}
              <p class="text-danger">Выбранная категория снята с публикации админом</p>
            {% endif %}
            {{ post.pub_date|date:"d E Y, H:i" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
            От автора <a class="text-muted" href="{% url 'blog:profile' post.author.username %}">@{{ post.author.username }}</a> в
            категории {% include "includes/category_link.html" %}
          </small>
        </h6>
        <p class="card-text">{{ post.text|linebreaksbr }}</p>
        {% if user == post.author %}
          <div class="mb-2">
            <a class="btn btn-sm text-muted" href="{% url 'blog:edit_post' post.id %}" role="button">
              Отредактировать публикацию
            </a>
            <a class="btn btn-sm text-muted" href="{% url 'blog:delete_post' post.id %}" role="button">
              Удалить публикацию
            </a>
          </div>
        {% endif %}
        {% include "includes/comments.html" %}
      </div>
    </div>
  </div>
{% endblock %}

blogicum/templates/blog/index.html
{% extends "base.html" %}
{% block title %}
  Лента записей
{% endblock %}
{% block content %}
  {% for post in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

blogicum/templates/blog/profile.html
{% extends "base.html" %}
{% block title %}
  Страница пользователя {{ profile }}
{% endblock %}
{% block content %}
  <h1 class="mb-5 text-center ">Страница пользователя {{ profile }}</h1>
  <small>
    <ul class="list-group list-group-horizontal justify-content-center mb-3">
      <li class="list-group-item text-muted">Имя пользователя: {% if profile.get_full_name %}{{ profile.get_full_name }}{% else %}не указано{% endif %}</li>
      <li class="list-group-item text-muted">Регистрация: {{ profile.date_joined }}</li>
      <li class="list-group-item text-muted">Роль: {% if profile.is_staff %}Админ{% else %}Пользователь{% endif %}</li>
    </ul>
    <ul class="list-group list-group-horizontal justify-content-center">
      {% if user.is_authenticated and request.user == profile %}
      <a class="btn btn-sm text-muted" href="{% url 'blog:edit_profile' pk=request.user.pk %}">Редактировать профиль</a>
      <a class="btn btn-sm text-muted" href="{% url 'password_change' %}">Изменить пароль</a>
      {% endif %}
    </ul>
  </small>
  <br>
  <h3 class="mb-5 text-center">Публикации пользователя</h3>
  {% for post in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

blogicum/templates/blog/user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Редактирование профиля
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Редактирование профиля - {{ request.user }}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}